/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ContractAddressesDto
 */
export interface ContractAddressesDto {
    /**
     * 
     * @type {string}
     * @memberof ContractAddressesDto
     */
    'CollateralToken': string;
    /**
     * 
     * @type {string}
     * @memberof ContractAddressesDto
     */
    'QuantProtocolMultisig': string;
    /**
     * 
     * @type {string}
     * @memberof ContractAddressesDto
     */
    'QuantWebMultisig': string;
    /**
     * 
     * @type {string}
     * @memberof ContractAddressesDto
     */
    'AssetsRegistry': string;
    /**
     * 
     * @type {string}
     * @memberof ContractAddressesDto
     */
    'OptionsFactory': string;
    /**
     * 
     * @type {string}
     * @memberof ContractAddressesDto
     */
    'PriceRegistry': string;
    /**
     * 
     * @type {string}
     * @memberof ContractAddressesDto
     */
    'OracleRegistry': string;
    /**
     * 
     * @type {string}
     * @memberof ContractAddressesDto
     */
    'ChainlinkOracleManager': string;
    /**
     * 
     * @type {string}
     * @memberof ContractAddressesDto
     */
    'ChainlinkFixedTimeOracleManager': string;
    /**
     * 
     * @type {string}
     * @memberof ContractAddressesDto
     */
    'QuantCalculator': string;
    /**
     * 
     * @type {string}
     * @memberof ContractAddressesDto
     */
    'Controller': string;
    /**
     * 
     * @type {string}
     * @memberof ContractAddressesDto
     */
    'RollaOrderProtocol': string;
    /**
     * 
     * @type {string}
     * @memberof ContractAddressesDto
     */
    'Whitelist': string;
    /**
     * 
     * @type {string}
     * @memberof ContractAddressesDto
     */
    'OperateProxy': string;
    /**
     * 
     * @type {string}
     * @memberof ContractAddressesDto
     */
    'RollaFaucet'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContractAddressesDto
     */
    'Multicall3'?: string;
}

