/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GasDetailsDto
 */
export interface GasDetailsDto {
    /**
     * 
     * @type {string}
     * @memberof GasDetailsDto
     */
    'LastBlock': string;
    /**
     * 
     * @type {string}
     * @memberof GasDetailsDto
     */
    'SafeGasPrice': string;
    /**
     * 
     * @type {string}
     * @memberof GasDetailsDto
     */
    'ProposeGasPrice': string;
    /**
     * 
     * @type {string}
     * @memberof GasDetailsDto
     */
    'FastGasPrice': string;
    /**
     * 
     * @type {string}
     * @memberof GasDetailsDto
     */
    'UsdPrice': string;
}

