/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LastLookResponseWithOrderSignatureDto
 */
export interface LastLookResponseWithOrderSignatureDto {
    /**
     * Blockchain transaction hash if accepted
     * @type {string}
     * @memberof LastLookResponseWithOrderSignatureDto
     */
    'transactionHash': string | null;
    /**
     * Market Maker Action
     * @type {string}
     * @memberof LastLookResponseWithOrderSignatureDto
     */
    'marketMakerAction': string;
    /**
     * order signature
     * @type {object}
     * @memberof LastLookResponseWithOrderSignatureDto
     */
    'orderSignature': object;
}

