/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MakerBalanceDto } from './maker-balance-dto';

/**
 * 
 * @export
 * @interface MakerOverviewDto
 */
export interface MakerOverviewDto {
    /**
     * Name of your account
     * @type {string}
     * @memberof MakerOverviewDto
     */
    'name': string;
    /**
     * Address of your account. Quotes must be signed from this address when providing
     * @type {string}
     * @memberof MakerOverviewDto
     */
    'address': string;
    /**
     * The endpoint we can send quote requests to
     * @type {string}
     * @memberof MakerOverviewDto
     */
    'quoteProviderUrl': string;
    /**
     * The endpoint we can send last look requests to
     * @type {string}
     * @memberof MakerOverviewDto
     */
    'lastLookUrl': string;
    /**
     * Whether or not we are sending quotes to you. If inactive or suspended, you may have told us to turn quotes off or you had too many failures against your account from cancellations, respectively
     * @type {string}
     * @memberof MakerOverviewDto
     */
    'status': MakerOverviewDtoStatusEnum;
    /**
     * Whether or not you support custom options
     * @type {boolean}
     * @memberof MakerOverviewDto
     */
    'supportsCustomOptions': boolean;
    /**
     * Cancellation timestamp on chain. Any quotes issued by you with a creationTimestamp less than this are invalid.
     * @type {string}
     * @memberof MakerOverviewDto
     */
    'makerCancelTime': string;
    /**
     * Array of balances which conform to object schema below.
     * @type {Array<MakerBalanceDto>}
     * @memberof MakerOverviewDto
     */
    'balances': Array<MakerBalanceDto>;
    /**
     * The addresses of tokens the market maker supports
     * @type {Array<string>}
     * @memberof MakerOverviewDto
     */
    'supportedAssets': Array<string>;
}

export const MakerOverviewDtoStatusEnum = {
    Active: 'ACTIVE',
    Inactive: 'INACTIVE',
    Suspended: 'SUSPENDED'
} as const;

export type MakerOverviewDtoStatusEnum = typeof MakerOverviewDtoStatusEnum[keyof typeof MakerOverviewDtoStatusEnum];


