/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MetaTransactionDtoOrder } from './meta-transaction-dto-order';

/**
 * 
 * @export
 * @interface MetaTransactionDto
 */
export interface MetaTransactionDto {
    /**
     * The function identifier to call in the ROP meta transaction. 0 = fill
     * @type {number}
     * @memberof MetaTransactionDto
     */
    'functionType': number;
    /**
     * Nonce of the meta transaction. This can be fetched by calling the nonce() method on the ROP contract
     * @type {number}
     * @memberof MetaTransactionDto
     */
    'nonce': number;
    /**
     * The unix timestamp (seconds) of when the meta transaction should become invalid
     * @type {string}
     * @memberof MetaTransactionDto
     */
    'deadline': string;
    /**
     * The from address of the meta transaction
     * @type {string}
     * @memberof MetaTransactionDto
     */
    'from': string;
    /**
     * 
     * @type {MetaTransactionDtoOrder}
     * @memberof MetaTransactionDto
     */
    'order': MetaTransactionDtoOrder;
    /**
     * Signature of the order
     * @type {object}
     * @memberof MetaTransactionDto
     */
    'signature': object;
    /**
     * Permit signature if an approval will be done with the meta transaction
     * @type {string}
     * @memberof MetaTransactionDto
     */
    'permit': string;
}

