/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OptionAttributesDto
 */
export interface OptionAttributesDto {
    /**
     * The address of the underlying asset on chain. The symbol can be looked up using the assets endpoint.
     * @type {string}
     * @memberof OptionAttributesDto
     */
    'underlyingAsset': string;
    /**
     * The address of the oracle on chain. This is used for settling the option post expiry
     * @type {string}
     * @memberof OptionAttributesDto
     */
    'oracle': string;
    /**
     * The strike price of the option. This is in whole units of the stablecoin currency.
     * @type {string}
     * @memberof OptionAttributesDto
     */
    'strikePrice': string;
    /**
     * The expiry time of the option as a unix timestamp in seconds.
     * @type {string}
     * @memberof OptionAttributesDto
     */
    'expiryTime': string;
    /**
     * Whether the option is a call or put.
     * @type {boolean}
     * @memberof OptionAttributesDto
     */
    'isCall': boolean;
}

