/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Max limit is 250
 * @export
 * @interface OptionMarketMakerControllerGetPriceRegistryEvents400Response
 */
export interface OptionMarketMakerControllerGetPriceRegistryEvents400Response {
    /**
     * 
     * @type {object}
     * @memberof OptionMarketMakerControllerGetPriceRegistryEvents400Response
     */
    'errorMessage': object;
    /**
     * 
     * @type {string}
     * @memberof OptionMarketMakerControllerGetPriceRegistryEvents400Response
     */
    'error': string;
}

