/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OptionAttributesDto } from './option-attributes-dto';

/**
 * @type OptionDtoOptionAttributes
 * Attributes of options. Each field in this object is defined below.
 * @export
 */
export type OptionDtoOptionAttributes = OptionAttributesDto;


