/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrderTrackingDto
 */
export interface OrderTrackingDto {
    /**
     * Integrator Address
     * @type {string}
     * @memberof OrderTrackingDto
     */
    'integrator': string;
    /**
     * Integrator commission percentage which will be sent to the integrator for referring the transaction
     * @type {string}
     * @memberof OrderTrackingDto
     */
    'integratorPercentage': string;
    /**
     * An optional tracking parameter for applications
     * @type {string}
     * @memberof OrderTrackingDto
     */
    'orderTag': string;
}

