/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PostMetaTransactionResponseDto
 */
export interface PostMetaTransactionResponseDto {
    /**
     * 
     * @type {string}
     * @memberof PostMetaTransactionResponseDto
     */
    'orderSignature': string;
    /**
     * responses to meta transaction requests
     * @type {string}
     * @memberof PostMetaTransactionResponseDto
     */
    'status': PostMetaTransactionResponseDtoStatusEnum;
}

export const PostMetaTransactionResponseDtoStatusEnum = {
    Success: 'SUCCESS',
    MetaTransactionDoesntExist: 'META_TRANSACTION_DOESNT_EXIST',
    IncorrectMaker: 'INCORRECT_MAKER',
    AlreadyRespondedToTransaction: 'ALREADY_RESPONDED_TO_TRANSACTION',
    OtherFailure: 'OTHER_FAILURE',
    ResponseWindowExpired: 'RESPONSE_WINDOW_EXPIRED'
} as const;

export type PostMetaTransactionResponseDtoStatusEnum = typeof PostMetaTransactionResponseDtoStatusEnum[keyof typeof PostMetaTransactionResponseDtoStatusEnum];


