/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PriceStoredDto
 */
export interface PriceStoredDto {
    /**
     * Actual settlement value in the base unit of the asset
     * @type {string}
     * @memberof PriceStoredDto
     */
    'settlementValue': string;
    /**
     * The unix timestamp when the price expires
     * @type {string}
     * @memberof PriceStoredDto
     */
    'expiryTimestamp': string;
    /**
     * unique identifier
     * @type {string}
     * @memberof PriceStoredDto
     */
    'uniqueEventId': string;
}

