/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OptionAttributesDto } from './option-attributes-dto';

/**
 * @type QuoteDtoOptionAttributes
 * The attributes of the option to be sold adhering to struct format above
 * @export
 */
export type QuoteDtoOptionAttributes = OptionAttributesDto;


