/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface QuoteResponseReplyDto
 */
export interface QuoteResponseReplyDto {
    /**
     * Quote response validity
     * @type {string}
     * @memberof QuoteResponseReplyDto
     */
    'validity': QuoteResponseReplyDtoValidityEnum;
    /**
     * Associated quote request id
     * @type {string}
     * @memberof QuoteResponseReplyDto
     */
    'quoteRequestId': string;
}

export const QuoteResponseReplyDtoValidityEnum = {
    ValidQuote: 'VALID_QUOTE',
    MarketMakerSkipped: 'MARKET_MAKER_SKIPPED',
    Timeout: 'TIMEOUT',
    InvalidQuote: 'INVALID_QUOTE',
    InsufficientBalance: 'INSUFFICIENT_BALANCE',
    InsufficientAllowance: 'INSUFFICIENT_ALLOWANCE',
    InvalidCancellationTimestamp: 'INVALID_CANCELLATION_TIMESTAMP',
    OtherFailure: 'OTHER_FAILURE',
    InvalidSignature: 'INVALID_SIGNATURE',
    RequestResponseMismatch: 'REQUEST_RESPONSE_MISMATCH',
    InvalidMaker: 'INVALID_MAKER',
    InvalidMakingAmount: 'INVALID_MAKING_AMOUNT',
    NoQuoteRequestForResponse: 'NO_QUOTE_REQUEST_FOR_RESPONSE',
    DuplicatedQuoteResponse: 'DUPLICATED_QUOTE_RESPONSE'
} as const;

export type QuoteResponseReplyDtoValidityEnum = typeof QuoteResponseReplyDtoValidityEnum[keyof typeof QuoteResponseReplyDtoValidityEnum];


