/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface QuoteResponseReplyDto
 */
export interface QuoteResponseReplyDto {
    /**
     * Quote response validity
     * @type {string}
     * @memberof QuoteResponseReplyDto
     */
    'validity': string;
    /**
     * Associated quote request id
     * @type {string}
     * @memberof QuoteResponseReplyDto
     */
    'quoteRequestId': string;
}

