/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { QuoteWithMetaDataDtoMetaData } from './quote-with-meta-data-dto-meta-data';
// May contain unused imports in some cases
// @ts-ignore
import { QuoteWithMetaDataDtoQuote } from './quote-with-meta-data-dto-quote';

/**
 * 
 * @export
 * @interface QuoteWithMetaDataDto
 */
export interface QuoteWithMetaDataDto {
    /**
     * 
     * @type {QuoteWithMetaDataDtoMetaData}
     * @memberof QuoteWithMetaDataDto
     */
    'metaData': QuoteWithMetaDataDtoMetaData;
    /**
     * 
     * @type {QuoteWithMetaDataDtoQuote}
     * @memberof QuoteWithMetaDataDto
     */
    'quote': QuoteWithMetaDataDtoQuote;
}

