/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { QuoteDtoOptionAttributes } from './quote-dto-option-attributes';

/**
 * 
 * @export
 * @interface QuoteRequestDto
 */
export interface QuoteRequestDto {
    /**
     * The timestamp when the order expires. If the block timestamp is after this timestamp when the order is submitted to the chain by the taker, the order will fail.
     * @type {string}
     * @memberof QuoteRequestDto
     */
    'orderExpirationTimestamp': string;
    /**
     * The address of the taker of the order (seller of options)
     * @type {string}
     * @memberof QuoteRequestDto
     */
    'taker': string;
    /**
     * The amount of options being sold in whole units - qTokens have 18 decimals
     * @type {string}
     * @memberof QuoteRequestDto
     */
    'takingAmount': string;
    /**
     * 
     * @type {QuoteDtoOptionAttributes}
     * @memberof QuoteRequestDto
     */
    'optionAttributes': QuoteDtoOptionAttributes;
    /**
     * The address of the asset that the option is being purchased with
     * @type {string}
     * @memberof QuoteRequestDto
     */
    'makerAsset': string;
}

