/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { QuoteDto } from './quote-dto';
// May contain unused imports in some cases
// @ts-ignore
import { QuoteDtoOptionAttributes } from './quote-dto-option-attributes';

/**
 * @type QuoteWithMetaDataDtoQuote
 * This is the quote object that was issued by you when we asked for a quote. This conforms to the order format previously covered.
 * @export
 */
export type QuoteWithMetaDataDtoQuote = QuoteDto;


