/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MetaTransactionDto } from './meta-transaction-dto';
// May contain unused imports in some cases
// @ts-ignore
import { MetaTransactionDtoOrder } from './meta-transaction-dto-order';
// May contain unused imports in some cases
// @ts-ignore
import { MetaTransactionDtoOrderTracking } from './meta-transaction-dto-order-tracking';

/**
 * @type SignedMetaTransactionDtoMetaTransaction
 * Meta transaction to submit
 * @export
 */
export type SignedMetaTransactionDtoMetaTransaction = MetaTransactionDto;


