/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OraclePricesDto } from './oracle-prices-dto';
// May contain unused imports in some cases
// @ts-ignore
import { PricesDto } from './prices-dto';

/**
 * @type SummaryDtoPrices
 * Prices summary
 * @export
 */
export type SummaryDtoPrices = OraclePricesDto;


