/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ConfigDto } from './config-dto';
// May contain unused imports in some cases
// @ts-ignore
import { ConfigDtoContractAddresses } from './config-dto-contract-addresses';
// May contain unused imports in some cases
// @ts-ignore
import { ConfigDtoFees } from './config-dto-fees';

/**
 * @type SummaryDtoConfig
 * Config summary
 * @export
 */
export type SummaryDtoConfig = ConfigDto;


