/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SupportsCustomOptionsDto
 */
export interface SupportsCustomOptionsDto {
    /**
     * whether the maker supports custom options
     * @type {boolean}
     * @memberof SupportsCustomOptionsDto
     */
    'supportsCustomOptions': boolean;
}

