/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OptionAttributesDto } from './option-attributes-dto';

/**
 * @type TradeDtoOptionAttributes
 * The attributes of the option that was traded. This conforms to the same format as the optionAttributes field on the get active options endpoint.
 * @export
 */
export type TradeDtoOptionAttributes = OptionAttributesDto;


