/* tslint:disable */
/* eslint-disable */
/**
 * Rolla Yield API - Market Maker
 * Rolla Yield API provides a RESTful API for fetching assets, options and quotes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TradeDtoOptionAttributes } from './trade-dto-option-attributes';

/**
 * 
 * @export
 * @interface TradeDto
 */
export interface TradeDto {
    /**
     * Rolla unique event id used for paginating
     * @type {string}
     * @memberof TradeDto
     */
    'uniqueEventId': string;
    /**
     * The address of the option token
     * @type {string}
     * @memberof TradeDto
     */
    'optionAddress': string;
    /**
     * The collateral token id associated with the option token
     * @type {string}
     * @memberof TradeDto
     */
    'collateralTokenId': string;
    /**
     * 
     * @type {TradeDtoOptionAttributes}
     * @memberof TradeDto
     */
    'optionAttributes': TradeDtoOptionAttributes;
    /**
     * The amount that was traded by the maker (premium). In partial fill scenarios (rare since UI doesnt support that) this will be different from the amount quoted. In normal fill scenarios this will be the amount quoted by the maker.
     * @type {string}
     * @memberof TradeDto
     */
    'makerAmount': string;
    /**
     * The amount of options the taker sold. In partial fill scenarios (rare since UI doesnt support that) this will be different from the taker amount from the quote. In normal fill scenarios this will be the same taker amount as the quote.
     * @type {string}
     * @memberof TradeDto
     */
    'takerAmount': string;
    /**
     * The amount the taker got for the trade. This will be the makerAmount after fees.
     * @type {string}
     * @memberof TradeDto
     */
    'takerPayout': string;
    /**
     * The underlying price from the oracle when the trade executed
     * @type {string}
     * @memberof TradeDto
     */
    'underlyingPriceWhenFilled': string;
    /**
     * The address of the maker
     * @type {string}
     * @memberof TradeDto
     */
    'makerAddress': string;
    /**
     * The premium asset paid by the maker
     * @type {string}
     * @memberof TradeDto
     */
    'makerAsset': string;
    /**
     * The address of the taker
     * @type {string}
     * @memberof TradeDto
     */
    'takerAddress': string;
    /**
     * The unix timestamp when the transaction took place
     * @type {string}
     * @memberof TradeDto
     */
    'transactionTime': string;
    /**
     * The hash of the transaction
     * @type {string}
     * @memberof TradeDto
     */
    'transactionHash': string;
    /**
     * The option symbol
     * @type {string}
     * @memberof TradeDto
     */
    'optionSymbol': string;
    /**
     * The settlement price of the option (if it has settled)
     * @type {string}
     * @memberof TradeDto
     */
    'settlementPrice': string | null;
    /**
     * Implied volatility of the option (%)
     * @type {number}
     * @memberof TradeDto
     */
    'impliedVolatility': number | null;
}

